auth_enabled: false
monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-prod-north-virginia
      ruler: loki-prod-north-virginia
    filesystem: null
    s3:
      s3: s3://us-east-1/loki-prod-north-virginia
      region: us-east-1
      secret_key_file: /etc/loki/secrets/credentials
      insecure: true
      s3forcepathstyle: true
  config:
    auth_enabled: false
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            period: 24h
            prefix: loki_index
    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 2048
          parallelism: 100
        memcached_client:
          consistent_hash: true
    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h
      poll_interval: 24m
    serviceMonitor:
      enabled: true
    ruler:
      alertmanager_url: http://prometheus-alertmanager.monitoring:9093
      enable_api: true
      enable_sharding: true
    promtail:
      serviceMonitor:
        enabled: true
  secrets:
    credentials:
      username: <your-access-key-id>
      password: <your-secret-access-key>
Note that the secret_key_file value has been replaced with a secrets section that defines the credentials secret containing the access_key_id and secret_access_key values. This allows the values to be accessed using the secretRef block as follows:


loki:
  storage:
    s3:
      accessKeyId: $(SECRET_NAME:username)
      secretAccessKey: $(SECRET_NAME:password)
Replace SECRET_NAME with the actual name of the secret containing the username and password values.
