# Set the deployment mode
mode: "daemonset"

# Enable the log collection preset with filelog receiver for daemonset
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    storeCheckpoints: true

# Base collector configuration for exporters and receivers
config:
  exporters:
    otlphttp:
      endpoint: 'http://tempo-distributed.tempo-dev.svc.local:4317'
      tls:
        insecure: true
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  service:
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - otlphttp

# ServiceAccount configurations
serviceAccount:
  name: "otel-collector-sa"

# Enable ports for OTLP, Jaeger, and Zipkin
ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
  jaeger-compact:
    enabled: true
  jaeger-thrift:
    enabled: true
  jaeger-grpc:
    enabled: true
  zipkin:
    enabled: true

# Resource requests and limits
resources:
  limits:
    cpu: 2000m
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Set the replica count for the deployment mode
replicaCount: 2
