otlp:
  http:
    enabled: true
    receiverConfig: {}

  grpc:
    enabled: true

metricsGenerator:
  enabled: true

  remote_write:
    - url: http://mimir-test-nginx.mimir-test.svc:80/api/v1/push

storage:
  backend: s3

  s3:
    endpoint: s3.us-east-1.amazonaws.com
    bucket: tempo-distributed
    region: us-east-1
    access_key: null
    secret_key: null
    insecure: false
