additionalPrometheusRulesMap:
  rule-name:
    groups:
    - name: ruleset_1
      rules:
      - alert: Node PIDPressure
        annotations:
          description: Node PIDPressure
          summary: Node PIDPressure
        expr: kube_node_status_condition{condition="PIDPressure"} == 0
        for: 0m
        labels:
          severity: warning
      - alert: PrometheusTargetMissing
        annotations:
          description: A Prometheus target has disappeared
          summary: Prometheus target missing
        expr: up == 0
        for: 0m
        labels:
          severity: critical
    - name: ruleset_2
      rules:
      - alert: Nodes with DiskPressure
        annotations:
          description: Nodes with DiskPressure
          summary: Nodes with DiskPressure
        expr: kube_node_status_condition{status="true", condition="DiskPressure"} == 0
        for: 0m
        labels:
          severity: critical
grafana:
  image:
    repository: grafana/grafana
    tag: 9.2.3
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 50Gi
    storageClassName: gp2
    type: pvc
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: http://mimir-test-nginx.mimir-test.svc:80/api/v1/push
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: gp2
