rbac:
  create: true

serviceAccount:
  create: true

securityContext:
  privileged: true

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 9090

resources: 
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 200Mi

updateStrategy:
  type: RollingUpdate

config:
  create: true
  data:
    otel_traces_export:
      endpoint: http://opentelemetry-collector.net/
      tls:
        insecure_skip_verify: true
    prometheus_export:
      port: 9090
      path: /metrics
