service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 9090
  annotations: {}
  labels: {}

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 200Mi

podSecurityContext: {}
securityContext:
  privileged: true

updateStrategy:
  type: RollingUpdate

nodeSelector: {}
tolerations: []
affinity: {}

config:
  create: true
  data:
    routes:
      unmatched: heuristic
    discovery:
      services:
        - k8s_namespace: .
    otel_traces_export:
      endpoint: http://opentelemetry-collector.otlp-collector.svc.cluster.local:4318/
      tls:
        insecure_skip_verify: true
    attributes:
      kubernetes:
        enable: true
    prometheus_export:
      port: 9090
      path: /metrics

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
